services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:17.0-alpine3.20
    volumes:
      - movies-db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  pgAdmin:
    depends_on:
      - db
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:8.12.0
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  
  # webApi:
  #   depends_on:
  #     - db
  #   container_name: ${API_CONTAINER_NAME}
  #   image: ${API_IMAGE_NAME}
  #   ports:
  #     - "${API_PORT:-3000}:${API_PORT:-3000}"
  #   environment:
  #     DB_HOST: ${DB_CONTAINER_NAME}
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     DB_DIALECT: ${DB_DIALECT}
  #     API_HOST: ${API_HOST}
  #     API_PORT: ${API_PORT}
  #     API_CLIENT_URL: ${API_CLIENT_URL}

volumes: 
  movies-db:
    external: true
  pgadmin:
    external: true